name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  integeration_tests:
    # Will not run if the event is a PR to bump-meilisearch-v* (so a pre-release PR)
    # Will still run for each push to bump-meilisearch-v*
    if: github.event_name != 'pull_request' || !startsWith(github.base_ref, 'bump-meilisearch-v')
    name: integration-tests
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
      GITHUB_PAT: ${{ secrets.MEILIBOT_PAT_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Download the latest stable version of Meilisearch
        run: |
          curl -L https://install.meilisearch.com | sh
          chmod +x meilisearch
      - name: Run Meilisearch
        run: |
          ./meilisearch --master-key=masterKey --no-analytics true &
      - name: Run tests
        run: swift test

  linter:
    name: linter-check
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run SwiftLint
        run: sh ./Scripts/swiftlint.sh
